import "./globals.css";
import { Suspense } from "react";
import Navbar from "@/components/navbar";
import SWRProvider from "@/components/swr-provider";

export const metadata = {
  title: "Elanco",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <Suspense>
          <Navbar />
        </Suspense>
        <SWRProvider>
          <main className="p-4 md:p-10 mx-auto max-w-7xl">{children}</main>
        </SWRProvider>
      </body>
    </html>
  );
}
